# Generated by Django 2.2.4 on 2020-03-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/merchant/%Y/%m/%d'),
        ),
    ]
