# Generated by Django 2.2.4 on 2020-03-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20200309_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/merchants/%Y/%m/%d'),
        ),
    ]
