# Generated by Django 2.2.4 on 2020-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200306_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('FR', 'fruits'), ('DA', 'Dairy'), ('OT', 'others'), ('PG', 'PaperGoods'), ('BEV', 'bevrages'), ('M', 'meat'), ('HE', 'herbs'), ('CL', 'cleaners'), ('VEG', 'veggies'), ('CG', 'CannedGoods'), ('UT', 'utensils'), ('SP', 'spices'), ('DBG', 'Dry/BakingGoods'), ('BR', 'Bread/Bakery')], default=None, max_length=120),
        ),
    ]
