# Generated by Django 2.2.4 on 2020-03-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200307_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('FR', 'fruits'), ('OT', 'others'), ('DBG', 'Dry/BakingGoods'), ('VEG', 'veggies'), ('SP', 'spices'), ('CL', 'cleaners'), ('HE', 'herbs'), ('BEV', 'bevrages'), ('CG', 'CannedGoods'), ('UT', 'utensils'), ('DA', 'Dairy'), ('BR', 'Bread/Bakery'), ('M', 'meat'), ('PG', 'PaperGoods')], default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
