# Generated by Django 2.2.4 on 2020-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200309_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('DA', 'Dairy'), ('CG', 'CannedGoods'), ('OT', 'others'), ('PG', 'PaperGoods'), ('FR', 'fruits'), ('M', 'meat'), ('HE', 'herbs'), ('VEG', 'veggies'), ('CL', 'cleaners'), ('DBG', 'Dry/BakingGoods'), ('UT', 'utensils'), ('BEV', 'bevrages'), ('BR', 'Bread/Bakery'), ('SP', 'spices')], default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
