# Generated by Django 2.2.4 on 2020-03-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200309_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('UT', 'utensils'), ('CL', 'cleaners'), ('PG', 'PaperGoods'), ('VEG', 'veggies'), ('DBG', 'Dry/BakingGoods'), ('FR', 'fruits'), ('OT', 'others'), ('DA', 'Dairy'), ('BR', 'Bread/Bakery'), ('HE', 'herbs'), ('BEV', 'bevrages'), ('M', 'meat'), ('CG', 'CannedGoods'), ('SP', 'spices')], default=None, max_length=120, null=True),
        ),
    ]
