# Generated by Django 2.2.4 on 2020-03-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200309_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('BEV', 'bevrages'), ('CL', 'cleaners'), ('PG', 'PaperGoods'), ('CG', 'CannedGoods'), ('SP', 'spices'), ('DBG', 'Dry/BakingGoods'), ('FR', 'fruits'), ('M', 'meat'), ('HE', 'herbs'), ('UT', 'utensils'), ('OT', 'others'), ('VEG', 'veggies'), ('BR', 'Bread/Bakery'), ('DA', 'Dairy')], default=None, max_length=120, null=True),
        ),
    ]
